# Generated by Django 3.2.20 on 2023-07-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.URLField()),
                ('preparation', models.TextField()),
                ('preparation_time', models.IntegerField()),
                ('type_cooking', models.CharField(choices=[('Stir Fry', 'Stir Fry'), ('Oven', 'Oven'), ('Stew', 'Stew'), ('Grill', 'Grill')], max_length=20)),
                ('oven_time', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('category', models.ForeignKey(default='category', on_delete=django.db.models.deletion.CASCADE, to='recipes_app.category')),
                ('subcategory', models.ForeignKey(default='subcategory', on_delete=django.db.models.deletion.CASCADE, to='recipes_app.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.FloatField()),
                ('measure', models.CharField(choices=[('Teaspoon', 'Teaspoon'), ('Spoon', 'Spoon'), ('Cup', 'Cup'), ('Kilo', 'Kilo')], max_length=10)),
                ('recipe', models.ForeignKey(default='recipe', on_delete=django.db.models.deletion.CASCADE, to='recipes_app.recipe')),
            ],
        ),
    ]
